services:
  openkylin:
    build:
      context: .
      dockerfile: Dockerfile
    image: eebpf-dev:latest
    container_name: openkylin-dev
    network_mode: host
    privileged: true
    cap_add:
      - BPF
      - PERFMON
      - SYS_RESOURCE
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - /sys/kernel/btf:/sys/kernel/btf:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:rw
      - /boot:/boot:ro
      - /sys:/sys:ro
      - /proc:/proc:ro
    restart: unless-stopped
