name: Project Build Test

on:
  push:
    branches: 
      - master
    paths:
      - src/**
      - include/**
      - Makefile
  workflow_dispatch:
  pull_request:
    branches: 
      - master

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/x2002w/eebpf-build:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /sys/kernel/btf:/sys/kernel/btf:ro

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make -j$(nproc)

      - name: 验证二进制
        run: test -x ./eebpf
